<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="crewai" nsURI="ecore://nasdanika.org/models/crew-ai" nsPrefix="org.nasdanika.models.crew-ai">
  <eClassifiers xsi:type="ecore:EClass" name="Code">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imports" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//Code ../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedStringIdentity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Guardrail" eSuperTypes="#//Function"/>
  <eClassifiers xsi:type="ecore:EClass" name="Callback" eSuperTypes="#//Function"/>
  <eClassifiers xsi:type="ecore:EClass" name="Configurable" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedStringIdentity #//Code">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="configuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tool" eSuperTypes="#//Code ../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedStringIdentity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="declarations" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agent" eSuperTypes="#//Configurable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tools" upperBound="-1"
        eType="#//Tool"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="llm" eType="#//LargeLanguageModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionCallingLlm" eType="#//LargeLanguageModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stepCallback" eType="#//Callback"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledgeSources" upperBound="-1"
        eType="#//KnowledgeSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="embedder" eType="#//Code"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Process">
    <eLiterals name="sequential"/>
    <eLiterals name="hierarchical" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Crew" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedStringIdentity #//Code">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tools" upperBound="-1"
        eType="#//Tool" containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//StringIdentity/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agents" upperBound="-1"
        eType="#//Agent" containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//StringIdentity/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task" containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//StringIdentity/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beforeKickoff" eType="#//Function"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="afterKickoff" eType="#//Function"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="process" eType="#//Process"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledgeSources" upperBound="-1"
        eType="#//KnowledgeSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="managerLlm" eType="#//LargeLanguageModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionCallingLlm" eType="#//LargeLanguageModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="planningLlm" eType="#//LargeLanguageModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="embedder" eType="#//Code"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//Configurable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="guardrail" eType="#//Guardrail"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agent" eType="#//Agent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tools" upperBound="-1"
        eType="#//Tool"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" upperBound="-1"
        eType="#//Task"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callback" eType="#//Callback"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LargeLanguageModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="KnowledgeSource"/>
</ecore:EPackage>
